import Head from "next/head";
import Layout from "../../components/Layout";
import Hero from "../../components/Home/Hero";
import AboutUs from "../../components/Home/AboutUs";
import BenefitSection from "../../components/Home/BenefitSection";
import LastSection from "../../components/Home/LastSection";

export default function Home() {
  return (
    // this is landing page of seaclub
    <Layout>
      <Head>
        <title>Seaclub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* the background only apply on hero AboutUs and BenefitSection */}
        <section className="bg-img">
          <Hero />
          <AboutUs />
          <BenefitSection />
        </section>
        <LastSection />
      </main>
    </Layout>
  );
}
