import Head from "next/head";
import Layout from "../../../components/Layout";
import styles from "../../styles/AboutUs.module.css";
import SeaClubStory from "../../../components/AboutUs/SeaClubStory";
import SeaClubVision from "../../../components/AboutUs/SeaClubVision";
import SeaClubTeam from "../../../components/AboutUs/SeaClubTeam";
import Footer from "../../../components/AboutUs/Footer";
const AboutUs = () => {
	return (
		<Layout>
			<Head>
				<title>About Us</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.container}>
                <div className={styles.aboutUs}>
				<SeaClubVision />
                <SeaClubStory />
                <SeaClubTeam/>
				<Footer />
                </div>
			</main>
		</Layout>
	);
};
export default AboutUs;
